const dummyProducts = [
  {
    name: "Floral Summer Dress",
    description: "Light and breezy for warm days.",
    price: 49.99,
    image: ["/images/floral.jpg"],
    category: "women",
    type: "topWear",
    sizes: ["S", "M", "L"],
    bestSeller: true,
    date: Date.now(),
  },
  {
    name: "Elegant Black Dress",
    description: "Perfect for evening events.",
    price: 89.99,
    image: ["/images/elegantBlackDress.jpg"],
    category: "women",
    type: "topWear",
    sizes: ["M", "L", "XL"],
    bestSeller: false,
    date: Date.now(),
  },
  {
    name: "Denim Shirt Dress",
    description: "Casual and cool.",
    price: 59.99,
    image: ["/images/DenimShirtDress.jpg"],
    category: "women",
    type: "topWear",
    sizes: ["S", "M", "L"],
    bestSeller: false,
    date: Date.now(),
  },
  {
    name: "Red Wrap Dress",
    description: "Stylish and comfortable.",
    price: 64.99,
    image: ["/images/redWrapDress.jpg"],
    category: "women",
    type: "topWear",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: true,
    date: Date.now(),
  },
  {
    name: "Boho Maxi Dress",
    description: "Free-spirited fashion.",
    price: 74.99,
    image: ["/images/bohoMaxiDress.jpg"],
    category: "women",
    type: "topWear",
    sizes: ["M", "L"],
    bestSeller: true,
    date: Date.now(),
  },
  {
    name: "Navy Bodycon Dress",
    description: "Fitted and flattering.",
    price: 69.99,
    image: ["/images/navyBodyCon.jpg"],
    category: "women",
    type: "bottomWear",
    sizes: ["S", "M"],
    bestSeller: false,
    date: Date.now(),
  },
  {
    name: "White Midi Dress",
    description: "Chic and timeless.",
    price: 79.99,
    image: ["/images/whiteMiddiDress.jpg"],
    category: "women",
    type: "bottomWear",
    sizes: ["S", "M", "L", "XL"],
    bestSeller: false,
    date: Date.now(),
  },
  {
    name: "Green Satin Dress",
    description: "Soft and elegant.",
    price: 89.99,
    image: ["/images/greenSatinDress.jpg"],
    category: "women",
    type: "winterWear",
    sizes: ["M", "L"],
    bestSeller: true,
    date: Date.now(),
  },
  {
    name: "Vintage Polka Dress",
    description: "Retro style.",
    price: 54.99,
    image: ["/images/vintagePolkaDress.jpg"],
    category: "men",
    type: "winterWear",
    sizes: ["S", "M", "L"],
    bestSeller: false,
    date: Date.now(),
  },
  {
    name: "Striped T-Shirt Dress",
    description: "Casual comfort.",
    price: 44.99,
    image: ["/images/strippedTshirt.jpg"],
    category: "men",
    type: "bottomWear",
    sizes: ["S", "M", "L"],
    bestSeller: false,
    date: Date.now(),
  },
];

export default dummyProducts;


// const dummyProducts = [
//   {
//     name: "Black tshirt",
//     description: "it is vey good",
//     price: 500,
//     image: [], // No image provided in the API data
//     category: "Clothing",
//     type: "Shirts",
//     sizes: ["XS", "S", "M", "L"],
//     bestSeller: true,
//     date: 1745235779901,
//   },
//   {
//     name: "Black tshirt",
//     description: "it is vey good",
//     price: 500,
//     image: [], // No image provided in the API data
//     category: "Clothing",
//     type: "Shirts",
//     sizes: ["XS", "S", "M", "L"],
//     bestSeller: true,
//     date: 1745235809409,
//   },
//   {
//     name: "Black tshirt",
//     description: "it is vey good",
//     price: 500,
//     image: [], // No image provided in the API data
//     category: "Clothing",
//     type: "Shirts",
//     sizes: ["XS", "S", "M", "L"],
//     bestSeller: true,
//     date: 1745235814484,
//   },
//   {
//     name: "etyu",
//     description: "tyu",
//     price: 56,
//     image: [
//       "https://res.cloudinary.com/dbhrxvgro/image/upload/v1745236162/vimlhto6gp4irtohgzth.jpg",
//     ],
//     category: "Clothing",
//     type: "Pants",
//     sizes: ["XS"],
//     bestSeller: true,
//     date: 1745236159931,
//   },
//   {
//     name: "3r56",
//     description: "yuio",
//     price: 77,
//     image: [
//       "https://res.cloudinary.com/dbhrxvgro/image/upload/v1745236354/bexfhali4jnv2loyr2ir.jpg",
//     ],
//     category: "Electronics",
//     type: "Smartphones",
//     sizes: ["S"],
//     bestSeller: true,
//     date: 1745236351580,
//   },
//   {
//     name: "r56",
//     description: "5678",
//     price: 98,
//     image: [
//       "https://res.cloudinary.com/dbhrxvgro/image/upload/v1745238800/q8oc7xysco7pgsutiqjn.jpg",
//     ],
//     category: "Clothing",
//     type: "Shirts",
//     sizes: ["S"],
//     bestSeller: true,
//     date: 1745238797952,
//   },
// ];

// export default dummyProducts;
